// Generated by gencpp from file robmovil_msgs/EncoderTicks.msg
// DO NOT EDIT!


#ifndef ROBMOVIL_MSGS_MESSAGE_ENCODERTICKS_H
#define ROBMOVIL_MSGS_MESSAGE_ENCODERTICKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>

namespace robmovil_msgs
{
template <class ContainerAllocator>
struct EncoderTicks_
{
  typedef EncoderTicks_<ContainerAllocator> Type;

  EncoderTicks_()
    : header()
    , ticks_left()
    , ticks_right()  {
    }
  EncoderTicks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ticks_left(_alloc)
    , ticks_right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _ticks_left_type;
  _ticks_left_type ticks_left;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _ticks_right_type;
  _ticks_right_type ticks_right;





  typedef boost::shared_ptr< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderTicks_

typedef ::robmovil_msgs::EncoderTicks_<std::allocator<void> > EncoderTicks;

typedef boost::shared_ptr< ::robmovil_msgs::EncoderTicks > EncoderTicksPtr;
typedef boost::shared_ptr< ::robmovil_msgs::EncoderTicks const> EncoderTicksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robmovil_msgs::EncoderTicks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robmovil_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robmovil_msgs': ['/home/mati/Documents/FinalRobotica2018-master/catkin_ws/src/robmovil_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "812913f836fe389b0d890bde3b74459e";
  }

  static const char* value(const ::robmovil_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x812913f836fe389bULL;
  static const uint64_t static_value2 = 0x0d890bde3b74459eULL;
};

template<class ContainerAllocator>
struct DataType< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robmovil_msgs/EncoderTicks";
  }

  static const char* value(const ::robmovil_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
std_msgs/Int32 ticks_left\n\
std_msgs/Int32 ticks_right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::robmovil_msgs::EncoderTicks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ticks_left);
      stream.next(m.ticks_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderTicks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robmovil_msgs::EncoderTicks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robmovil_msgs::EncoderTicks_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ticks_left: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.ticks_left);
    s << indent << "ticks_right: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.ticks_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBMOVIL_MSGS_MESSAGE_ENCODERTICKS_H
